version: "3.8"
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx_proxy_sub
    networks:
      web:
    env_file:
      - .env
    volumes:
      - ${PATH_SSL_KEY}/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - ${PATH_SSL_KEY}/privkey.pem:/etc/nginx/ssl/privkey.pem
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.entrypoints=https"
      - "traefik.http.routers.nginx.rule=Host(`subserver.example`)"
      - "traefik.http.routers.nginx.tls=true"
      - "traefik.http.routers.nginx.tls.certresolver=lets"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
      - "traefik.docker.network=web"
    restart: always

networks:
  web:
    external: true